---

- name: assert that cloudformation array has required elements
  assert:
    that:
      - item.stack_name is defined
      - item.template is defined
  with_items:
    - "{{ cloudformation_stacks }}"

- name: assert custom set required keys in cloudformation array
  assert:
    that:
      - item[0].item[1] is defined
  with_nested:
    - "{{ cloudformation_stacks }}"
    - "{{ cloudformation_required }}"
