---

- name: assert that cloudformation array has required elements
  assert:
    that:
      - item.stack_name is defined
      - item.template is defined
  with_items:
    - "{{ cloudformation_stacks }}"

- name: assert custom set required keys in cloudformation array
  assert:
    that:
      - "item[0][item[1]] is defined"
    msg: "Stack '{{ item[0].stack_name }}' has no dict key {{ item[1] }}"
  with_nested:
    - "{{ cloudformation_stacks }}"
    - "{{ cloudformation_required }}"

- name: assert that cloudformation_diff output is set correctly
  assert:
    that:
      - "cloudformation_diff_output == 'yaml' or cloudformation_diff_output == 'json'"
    msg: "cloudformation_diff_output must either be 'yaml' or 'json', but not: '{{ cloudformation_diff_output }}'"
